In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("bank_dataset.csv")

In [3]:
data.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
age          11162 non-null int64
job          11162 non-null object
marital      11162 non-null object
education    11162 non-null object
default      11162 non-null object
balance      11162 non-null int64
housing      11162 non-null object
loan         11162 non-null object
contact      11162 non-null object
day          11162 non-null int64
month        11162 non-null object
duration     11162 non-null int64
campaign     11162 non-null int64
pdays        11162 non-null int64
previous     11162 non-null int64
poutcome     11162 non-null object
deposit      11162 non-null object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [6]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [7]:
x=data.iloc[:,:16].values
y=data.iloc[:,16].values

In [8]:
from sklearn.preprocessing import OneHotEncoder#creates columns based on categories of textual data
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder="passthrough")#add columns to first
x=ct.fit_transform(x)

In [9]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [10]:
y

array(['yes', 'yes', 'yes', ..., 'no', 'no', 'no'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [12]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10000)

In [14]:
x_train

array([[0.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 30, -1, 0],
       [0.0, 0.0, 0.0, ..., 3, -1, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 4, -1, 0],
       [0.0, 0.0, 0.0, ..., 3, -1, 0],
       [0.0, 1.0, 0.0, ..., 8, -1, 0]], dtype=object)

In [15]:
y_train

array([0, 0, 1, ..., 0, 0, 0])

In [16]:
x_test

array([[0.0, 0.0, 0.0, ..., 5, -1, 0],
       [0.0, 1.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, 182, 2],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 6, -1, 0]], dtype=object)

In [17]:
y_test

array([0, 0, 1, ..., 0, 0, 0])

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [19]:
x_train

array([[-0.36426721, -0.46260575, -0.1693713 , ..., -0.56446046,
        -0.47466251, -0.35339114],
       [-0.36426721, -0.46260575, -0.1693713 , ..., 10.21603495,
        -0.47466251, -0.35339114],
       [-0.36426721, -0.46260575, -0.1693713 , ...,  0.17902198,
        -0.47466251, -0.35339114],
       ...,
       [-0.36426721, -0.46260575,  5.90418815, ...,  0.5507632 ,
        -0.47466251, -0.35339114],
       [-0.36426721, -0.46260575, -0.1693713 , ...,  0.17902198,
        -0.47466251, -0.35339114],
       [-0.36426721,  2.16166791, -0.1693713 , ...,  2.03772808,
        -0.47466251, -0.35339114]])

In [20]:
x_test

array([[-0.38480122, -0.44565054, -0.19150966, ...,  0.88963344,
        -0.50714558, -0.40546216],
       [-0.38480122,  2.24391068, -0.19150966, ..., -0.51602831,
        -0.50714558, -0.40546216],
       [ 2.59874435, -0.44565054, -0.19150966, ..., -0.51602831,
         1.14656309,  0.50585843],
       ...,
       [-0.38480122, -0.44565054, -0.19150966, ..., -0.16461288,
        -0.50714558, -0.40546216],
       [ 2.59874435, -0.44565054, -0.19150966, ..., -0.51602831,
        -0.50714558, -0.40546216],
       [ 2.59874435, -0.44565054, -0.19150966, ...,  1.24104888,
        -0.50714558, -0.40546216]])

In [21]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
a=logreg.fit(x_train,y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [22]:
a

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
ypreg=logreg.predict(x_test)

In [24]:
ypreg

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
y_test

array([0, 0, 1, ..., 0, 0, 0])

In [26]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(ypreg,y_test)

In [27]:
accuracy

0.8320644872369011

In [30]:
a=logreg.predict(sc.transform(ct.transform([[51,"admin.","married","secondary","no",2343,"yes","yes","unknown",51,"may",1042,1,-1,0,"unknown"]])))


In [31]:
a

array([1])

In [32]:
data.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [33]:
data.job.unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

# ANN

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [36]:
bank=Sequential()

In [37]:
x.shape

(11162, 51)

In [38]:
data.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [39]:
bank.add(Dense(51,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [40]:
y.shape

(11162,)

In [41]:
bank.add(Dense(102,kernel_initializer="random_uniform",activation="relu"))

In [42]:
bank.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [43]:
bank.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [44]:
bank.fit(x_train,y_train,batch_size=32,epochs=50)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/50
8929/8929 [==============================] - 1s 168us/sample - loss: 0.4591 - acc: 0.7863
Epoch 2/50
8929/8929 [==============================] - 0s 54us/sample - loss: 0.3658 - acc: 0.8439
Epoch 3/50
8929/8929 [==============================] - 1s 60us/sample - loss: 0.3519 - acc: 0.8500
Epoch 4/50
8929/8929 [==============================] - 1s 59us/sample - loss: 0.3407 - acc: 0.8556
Epoch 5/50
8929/8929 [==============================] - 1s 58us/sample - loss: 0.3337 - acc: 0.8603
Epoch 6/50
8929/8929 [==============================] - 1s 57us/sample - loss: 0.3283 - acc: 0.8615
Epoch 7/50
8929/8929 [==============================] - 1s 62us/sample - loss: 0.3225 - acc: 0.8643
Epoch 8/50
8929/8929 [==============================] - 0s 55us/sample - loss: 0.3145 - acc: 0.8718
Epoch 9/50
8929/8929 [==============================] - 0s 54us/sample - loss: 0.3125 - acc: 0.8715
Epoch

In [45]:
ypred=bank.predict(x_test)

In [46]:
ypred

array([[0.        ],
       [0.00330538],
       [0.03157467],
       ...,
       [0.05367607],
       [0.20024312],
       [0.        ]], dtype=float32)

In [47]:
y_test

array([0, 0, 1, ..., 0, 0, 0])

In [48]:
ypred[1]

array([0.00330538], dtype=float32)

In [49]:
y_test[1]

0

In [50]:
a=bank.predict_classes(sc.transform(ct.transform([[51,"admin.","married","secondary","no",2343,"yes","no","unknown",51,"may",1042,1,-1,0,"unknown"]])))

In [51]:
a

array([[1]])

In [52]:
a=bank.predict_classes(sc.transform(ct.transform([[51,"admin.","married","secondary","no",2343,"yes","no","unknown",51,"may",1042,2,-1,1,"unknown"]])))

In [53]:
a

array([[1]])